Repository DDD-Community/DDD-9-Android2-Sikdorok, pull requests merged in 2023-08, with the labels that each got.

#15 [ chore ] : 식도록 프리퍼런스 모듈 생성 완료
  data/src/main/java/com/ddd/sikdorok/data/SikdorokPreference.kt
  preference/.gitignore
  preference/build.gradle
  preference/consumer-rules.pro
  preference/proguard-rules.pro
  preference/src/androidTest/java/com/ddd/sikdorok/preference/ExampleInstrumentedTest.kt
  preference/src/main/AndroidManifest.xml
  preference/src/main/java/com/ddd/sikdorok/preference/SikdorokPrefernceImpl.kt
  preference/src/test/java/com/ddd/sikdorok/preference/ExampleUnitTest.kt
  settings.gradle
  shared/src/main/java/com/ddd/sikdorok/shared/key/key.kt
Labels: 신규기능, 진행중

#21 [ Feature ] : 비밀번호 찾기 이메일전송 화면 구현완료
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/ddd/sikdorok/di/Coordinator.kt
  app/src/main/java/com/ddd/sikdorok/navigator/SendPasswordNavigatorImpl.kt
  core-design/src/main/res/drawable/ic_info.xml
  core-design/src/main/res/drawable/ic_success.xml
  core-design/src/main/res/values/colors.xml
  feature/send-password/.gitignore
  feature/send-password/build.gradle
  feature/send-password/consumer-rules.pro
  feature/send-password/proguard-rules.pro
  feature/send-password/src/androidTest/java/com/ddd/sikdorok/send_password/ExampleInstrumentedTest.kt
  feature/send-password/src/main/AndroidManifest.xml
  feature/send-password/src/main/java/com/ddd/sikdorok/send_password/SendPasswordActivity.kt
  feature/send-password/src/main/res/layout/activity_send_password.xml
  feature/send-password/src/main/res/values/strings.xml
  feature/send-password/src/test/java/com/ddd/sikdorok/send_password/ExampleUnitTest.kt
  navigator/.DS_Store
  navigator/send-password/.gitignore
  navigator/send-password/build.gradle
  navigator/send-password/consumer-rules.pro
  navigator/send-password/proguard-rules.pro
  navigator/send-password/src/main/AndroidManifest.xml
  navigator/send-password/src/main/java/com/ddd/sikdorok/send_password/SendPasswordNavigator.kt
  settings.gradle
Labels: 신규기능, 디자인추가

#20 [ Feature ] : 비밀번호 찾기 mvi 구조 구현 완료 및 로직 연결
  core-api/src/main/java/com/ddd/sikdorok/core_api/ServiceModule.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/password/PasswordRemoteDataSourceImpl.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/service/UserService.kt
  data/src/main/java/com/ddd/sikdorok/data/password/PasswordRepositoryImpl.kt
  data/src/main/java/com/ddd/sikdorok/data/password/data/PasswordRemoteDataSource.kt
  domain/src/main/java/com/ddd/sikdorok/domain/password/PostFindPasswordUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/repository/PasswordRepository.kt
  extensions/src/main/java/com/ddd/sikdorok/extensions/networkExtension.kt
  feature/find-password/build.gradle
  feature/find-password/src/main/java/com/ddd/sikdorok/find_password/FindPasswordActivity.kt
  feature/find-password/src/main/java/com/ddd/sikdorok/find_password/FindPasswordContract.kt
  feature/find-password/src/main/java/com/ddd/sikdorok/find_password/FindPasswordViewModel.kt
  feature/find-password/src/main/res/layout/activity_find_password.xml
Labels: 신규기능

#19 [ Feature ] : 식도록 비밀번호 찾기 디자인 구현 완료
  core-api/src/main/java/com/ddd/sikdorok/core_api/ServiceModule.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/password/PasswordRemoteDataSourceImpl.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/service/UserService.kt
  data/src/main/java/com/ddd/sikdorok/data/password/PasswordRepositoryImpl.kt
  data/src/main/java/com/ddd/sikdorok/data/password/data/PasswordRemoteDataSource.kt
  domain/src/main/java/com/ddd/sikdorok/domain/password/PostFindPasswordUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/repository/PasswordRepository.kt
  extensions/src/main/java/com/ddd/sikdorok/extensions/networkExtension.kt
  feature/find-password/build.gradle
  feature/find-password/src/main/java/com/ddd/sikdorok/find_password/FindPasswordActivity.kt
  feature/find-password/src/main/java/com/ddd/sikdorok/find_password/FindPasswordContract.kt
  feature/find-password/src/main/java/com/ddd/sikdorok/find_password/FindPasswordViewModel.kt
  feature/find-password/src/main/res/layout/activity_find_password.xml
  feature/find-password/src/main/res/values/strings.xml
Labels: 신규기능, 디자인추가

#18 [ Feature ] : 식도록 이메일 회원가입 시 정규식 체크 추가
  feature/signup/src/main/java/com/ddd/sikdorok/signup/SignUpActivity.kt
  feature/signup/src/main/java/com/ddd/sikdorok/signup/SignUpContract.kt
  feature/signup/src/main/java/com/ddd/sikdorok/signup/SignUpViewModel.kt
  feature/signup/src/main/res/values/strings.xml
Labels: 신규기능

#23 [ Refactor ] : 회원가입 시 비밀번호 정규식 수정
  feature/signup/src/main/java/com/ddd/sikdorok/signup/SignUpViewModel.kt
Labels: 신규기능

#22 [ Feature ] : 식도록 회원가입 이메일 유효성 검사 로직 추가
  core-api/src/main/java/com/ddd/sikdorok/core_api/login/LoginRemoteDataSourceImpl.kt
  data/src/main/java/com/ddd/sikdorok/data/login/LoginRepositoryImpl.kt
  data/src/main/java/com/ddd/sikdorok/data/login/data/LoginRemoteDataSource.kt
  domain/src/main/java/com/ddd/sikdorok/domain/email/PostOnCheckEmailUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/repository/LoginRepository.kt
  feature/signup/src/main/java/com/ddd/sikdorok/signup/SignUpViewModel.kt
Labels: 신규기능

#11 [ Feature ] : Firebase Dynamic Links 연동
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
  gradle/libs.versions.toml
Labels: 신규기능

#25 [ Feature ] : 식도록 피쳐 백키 공통화 액티비티 생성
  .gitignore
  app/build.gradle
  core-ui/build.gradle
  core-ui/src/androidTest/java/com/example/core_ui/ExampleInstrumentedTest.kt
  core-ui/src/main/java/com/ddd/sikdorok/core_ui/base/BackFrameActivity.kt
  core-ui/src/main/java/com/ddd/sikdorok/core_ui/base/BaseActivity.kt
  core-ui/src/main/java/com/ddd/sikdorok/core_ui/base/BaseBottomSheetFragment.kt
  core-ui/src/main/java/com/ddd/sikdorok/core_ui/base/BaseContract.kt
  core-ui/src/main/java/com/ddd/sikdorok/core_ui/base/BaseDialogFragment.kt
  core-ui/src/main/java/com/ddd/sikdorok/core_ui/base/BaseFragment.kt
  core-ui/src/main/java/com/ddd/sikdorok/core_ui/base/BaseViewModel.kt
  core-ui/src/main/java/com/example/core_ui/base/BaseViewModel.kt
  core-ui/src/test/java/com/example/core_ui/ExampleUnitTest.kt
  data/src/main/java/com/ddd/sikdorok/data/login/LoginRepositoryImpl.kt
  domain/src/main/java/com/ddd/sikdorok/domain/login/PostSaveTokenUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/repository/LoginRepository.kt
  extensions/build.gradle
  extensions/src/main/java/com/ddd/sikdorok/extensions/contextExtension.kt
  feature/find-password/src/main/java/com/ddd/sikdorok/find_password/FindPasswordActivity.kt
  feature/find-password/src/main/java/com/ddd/sikdorok/find_password/FindPasswordViewModel.kt
  feature/login/src/main/java/com/ddd/sikdorok/login/LoginActivity.kt
  feature/login/src/main/java/com/ddd/sikdorok/login/LoginViewModel.kt
  feature/send-password/src/main/java/com/ddd/sikdorok/send_password/SendPasswordActivity.kt
  feature/signin/src/main/java/com/ddd/sikdorok/signin/SignInActivity.kt
  feature/signin/src/main/java/com/ddd/sikdorok/signin/SignInViewModel.kt
  feature/signup/src/main/java/com/ddd/sikdorok/signup/SignUpActivity.kt
  feature/signup/src/main/java/com/ddd/sikdorok/signup/SignUpContract.kt
  feature/signup/src/main/java/com/ddd/sikdorok/signup/SignUpViewModel.kt
  gradle/libs.versions.toml
  shared/src/main/java/com/ddd/sikdorok/shared/base/SikdorokResponse.kt
  shared/src/main/java/com/ddd/sikdorok/shared/login/Login.kt
  shared/src/main/java/com/ddd/sikdorok/shared/login/TokenType.kt
Labels: 신규기능

#28 [ Feature ] : 환경설정 피처 작업 완료
  app/build.gradle
  app/src/main/AndroidManifest.xml
  core-design/src/main/res/drawable/ic_arrow_right_down.xml
  extensions/src/main/java/com/ddd/sikdorok/extensions/contentExtension.kt
  feature/settings/.gitignore
  feature/settings/build.gradle
  feature/settings/consumer-rules.pro
  feature/settings/proguard-rules.pro
  feature/settings/src/androidTest/java/com/ddd/sikdorok/settings/ExampleInstrumentedTest.kt
  feature/settings/src/main/AndroidManifest.xml
  feature/settings/src/main/java/com/ddd/sikdorok/settings/SettingActivity.kt
  feature/settings/src/main/res/layout/activity_setting.xml
  feature/settings/src/main/res/values/strings.xml
  feature/settings/src/test/java/com/ddd/sikdorok/settings/ExampleUnitTest.kt
  settings.gradle
Labels: 신규기능, 디자인추가

#31 [ Feature ] : 환경설정 네비게이션 모듈 연결
  app/build.gradle
  app/src/main/java/com/ddd/sikdorok/di/Coordinator.kt
  app/src/main/java/com/ddd/sikdorok/navigator/DeleteAccountNavigatorImpl.kt
  app/src/main/java/com/ddd/sikdorok/navigator/ManagementNavigatorImpl.kt
  navigator/delete-account/.gitignore
  navigator/delete-account/build.gradle
  navigator/delete-account/consumer-rules.pro
  navigator/delete-account/proguard-rules.pro
  navigator/delete-account/src/main/AndroidManifest.xml
  navigator/delete-account/src/main/java/com/ddd/sikdorok/navigator/delete_account/DeleteAccountNavigator.kt
  navigator/management/.gitignore
  navigator/management/build.gradle
  navigator/management/consumer-rules.pro
  navigator/management/proguard-rules.pro
  navigator/management/src/main/AndroidManifest.xml
  navigator/management/src/main/java/com/ddd/sikdorok/navigator/management/ManagementNavigator.kt
  settings.gradle
Labels: 신규기능

#33 [ Feature ] : 식도록 로그인 화면 디자인 적용
  core-design/src/main/res/drawable-hdpi/ic_signup.png
  core-design/src/main/res/drawable-mdpi/ic_signup.png
  core-design/src/main/res/drawable-xhdpi/ic_signup.png
  core-design/src/main/res/drawable-xxhdpi/ic_signup.png
  core-design/src/main/res/drawable-xxxhdpi/ic_signup.png
  core-design/src/main/res/drawable/ic_kakao.xml
  core-design/src/main/res/drawable/shape_corner6_bg_email_login_color.xml
  core-design/src/main/res/drawable/shape_corner6_bg_yellow.xml
  core-design/src/main/res/values/colors.xml
  core-design/src/main/res/values/themes.xml
  feature/login/src/main/res/layout/activity_login.xml
  feature/login/src/main/res/values/strings.xml
Labels: 디자인추가

#34 [ Feature ] : 계정삭제 디자인 적용 완료
  app/src/main/AndroidManifest.xml
  core-design/src/main/res/drawable-hdpi/ic_delete_account.png
  core-design/src/main/res/drawable-mdpi/ic_delete_account.png
  core-design/src/main/res/drawable-xhdpi/ic_delete_account.png
  core-design/src/main/res/drawable-xxhdpi/ic_delete_account.png
  core-design/src/main/res/drawable-xxxhdpi/ic_delete_account.png
  core-design/src/main/res/drawable/ic_tooltip_delete.xml
  extensions/src/main/java/com/ddd/sikdorok/extensions/viewExtenstion.kt
  feature/delete-account/build.gradle
  feature/delete-account/src/main/AndroidManifest.xml
  feature/delete-account/src/main/java/com/ddd/sikdorok/delete_account/DeleteAccountActivity.kt
  feature/delete-account/src/main/res/layout/activity_delete_account.xml
  feature/delete-account/src/main/res/values/strings.xml
Labels: 디자인추가

#37 [ Feature ] : 회원탈퇴 서비스 로직 연결
  core-api/src/main/java/com/ddd/sikdorok/core_api/ServiceModule.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/service/UserService.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/withdraw/UserWithDrawRemoteDataSourceImpl.kt
  data/src/main/java/com/ddd/sikdorok/data/withdraw/UserWithDrawRepositoryImpl.kt
  data/src/main/java/com/ddd/sikdorok/data/withdraw/data/UserWithdrawRemoteDataSource.kt
  domain/src/main/java/com/ddd/sikdorok/domain/repository/UserWithDrawRepository.kt
  domain/src/main/java/com/ddd/sikdorok/domain/withdraw/DeleteUserWithDrawUseCase.kt
Labels: 신규기능

#36 [ Feature ] : 피드 관련 서비스 로직 추가 및 연결
  core-api/src/main/java/com/ddd/sikdorok/core_api/ServiceModule.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/modify/ModifyRemoteDataSourceImpl.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/service/ModifyService.kt
  data/src/main/java/com/ddd/sikdorok/data/modify/ModifyRepositoryImpl.kt
  data/src/main/java/com/ddd/sikdorok/data/modify/data/ModifyRemoteDataSource.kt
  domain/src/main/java/com/ddd/sikdorok/domain/modify/CreateFeedUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/modify/DeleteFeedUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/modify/UpdateFeedUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/repository/ModifyRepository.kt
  shared/src/main/java/com/ddd/sikdorok/shared/code/networkCode.kt
  shared/src/main/java/com/ddd/sikdorok/shared/modify/FeedRequest.kt
Labels: 신규기능

#40 [ Feature ] : 식도록 로컬 로그인 로직 구현 완료
  core-api/src/main/java/com/ddd/sikdorok/core_api/login/LoginRemoteDataSourceImpl.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/service/UserService.kt
  data/src/main/java/com/ddd/sikdorok/data/login/LoginRepositoryImpl.kt
  data/src/main/java/com/ddd/sikdorok/data/login/data/LoginRemoteDataSource.kt
  domain/src/main/java/com/ddd/sikdorok/domain/login/PostSikdorokLocalLoginUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/repository/LoginRepository.kt
  feature/signin/build.gradle
  feature/signin/src/main/java/com/ddd/sikdorok/signin/SignInActivity.kt
  feature/signin/src/main/java/com/ddd/sikdorok/signin/SignInContract.kt
  feature/signin/src/main/java/com/ddd/sikdorok/signin/SignInViewModel.kt
  feature/signin/src/main/res/layout/activity_sign_in.xml
Labels: 신규기능

#39 [ Feature ] : 기기에 저장된 토큰에 따른 화면이동 로직 구현
  core-api/src/main/java/com/ddd/sikdorok/core_api/login/LoginRemoteDataSourceImpl.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/service/UserService.kt
  data/src/main/java/com/ddd/sikdorok/data/login/LoginRepositoryImpl.kt
  data/src/main/java/com/ddd/sikdorok/data/login/data/LoginRemoteDataSource.kt
  domain/src/main/java/com/ddd/sikdorok/domain/login/GetSavedTokenUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/login/PostSikdorokLocalLoginUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/repository/LoginRepository.kt
  feature/signin/build.gradle
  feature/signin/src/main/java/com/ddd/sikdorok/signin/SignInActivity.kt
  feature/signin/src/main/java/com/ddd/sikdorok/signin/SignInContract.kt
  feature/signin/src/main/java/com/ddd/sikdorok/signin/SignInViewModel.kt
  feature/signin/src/main/res/layout/activity_sign_in.xml
  feature/splash/build.gradle
  feature/splash/src/main/java/com/ddd/sikdorok/splash/SplashActivity.kt
  feature/splash/src/main/java/com/ddd/sikdorok/splash/SplashContract.kt
  feature/splash/src/main/java/com/ddd/sikdorok/splash/SplashViewModel.kt
Labels: 신규기능

#38 [ Feature ] : 로그인 네비게이션 모듈 로직 구현 완료
  app/build.gradle
  app/src/main/java/com/ddd/sikdorok/di/Coordinator.kt
  app/src/main/java/com/ddd/sikdorok/navigator/LoginNavigatorImpl.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/login/LoginRemoteDataSourceImpl.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/service/UserService.kt
  data/src/main/java/com/ddd/sikdorok/data/login/LoginRepositoryImpl.kt
  data/src/main/java/com/ddd/sikdorok/data/login/data/LoginRemoteDataSource.kt
  domain/src/main/java/com/ddd/sikdorok/domain/login/GetSavedTokenUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/login/PostSikdorokLocalLoginUseCase.kt
  domain/src/main/java/com/ddd/sikdorok/domain/repository/LoginRepository.kt
  feature/signin/build.gradle
  feature/signin/src/main/java/com/ddd/sikdorok/signin/SignInActivity.kt
  feature/signin/src/main/java/com/ddd/sikdorok/signin/SignInContract.kt
  feature/signin/src/main/java/com/ddd/sikdorok/signin/SignInViewModel.kt
  feature/signin/src/main/res/layout/activity_sign_in.xml
  feature/splash/build.gradle
  feature/splash/src/main/java/com/ddd/sikdorok/splash/SplashActivity.kt
  feature/splash/src/main/java/com/ddd/sikdorok/splash/SplashContract.kt
  feature/splash/src/main/java/com/ddd/sikdorok/splash/SplashViewModel.kt
  navigator/login/.gitignore
  navigator/login/build.gradle
  navigator/login/consumer-rules.pro
  navigator/login/proguard-rules.pro
  navigator/login/src/main/AndroidManifest.xml
  navigator/login/src/main/java/com/ddd/sikdorok/navigator/login/LoginNavigator.kt
  settings.gradle
Labels: 신규기능

#41 [ Feature ] : 식도록 api 호출 시 인터셉터 구현 완료
  core-api/build.gradle
  core-api/src/main/java/com/ddd/sikdorok/core_api/NetworkModule.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/ServiceModule.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/annotation/annotation.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/interceptor/AccessTokenInterceptor.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/interceptor/RefreshTokenInterceptor.kt
  core-api/src/main/java/com/ddd/sikdorok/core_api/service/UserService.kt
  feature/modify/src/main/res/layout/activity_modify.xml
  shared/src/main/java/com/ddd/sikdorok/shared/login/Login.kt
Labels: 신규기능
